### ISSUE TITLE
Django app

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#1]
- [ ] Create a django app that contains this model:

```python
class EpuIndexScore(models.Model):
    date = models.DateField()
    number_of_articles = models.IntegerField()
    number_of_papers = models.IntegerField()
    epu = models.FloatField()
```

- [ ] Install app and database on a preferably free service.
- [ ] Load data (which I will provide) in the database.

**Comment by peterdesmet** [comment]
We should not disclose login info in this public repo. Best to update.

**Comment by peterdesmet** [comment]
Will this endpoint be used in production? Please update the logins and send by email.
