### ISSUE TITLE
Q&A

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#10]
# Q

- [x] Which resolution is needed for the line chart?
- [x] Should the linechart show data from several years at once?
- [x] What is the most important aspect: trends or outliers?

**Comment by bartaelterman** [comment]
# A
- The main line chart should show the data per day
- Yes, but this can be done in a context (small line chart below the main one). Or by simplifying the main line chart (using [Simplify.js](http://mourner.github.io/simplify-js/) for instance)
- The trend is the most important aspect.

**Comment by peterdesmet** [comment]
Picked up again and documented in several issues.
