### ISSUE TITLE
Filter on epu index enpoint

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#11]
The frontend cannot handle all epu index data and querying all data from the backend takes a significant time to load:

![screen shot 2015-05-11 at 21 38 00](https://cloud.githubusercontent.com/assets/2742677/7573465/13857808-f826-11e4-884b-49321ca32a71.png)

Therefore, it would be better if we could filter the data by letting the epu index endpoint accept a `start` and `end` parameter, both accepting a date in `yyyy-mm-dd` format.

**Comment by niconoe** [comment]
Done, note the filters are inclusive (<= / >=)
