### ISSUE TITLE
Backend should serve a csv containing all epu index data

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#12]
The user is able to download all epu index data using the website. Currently, all communication between front end and backend is done using the REST protocol. I'm not sure whether we should stick to that for this download functionality.

**Comment by niconoe** [comment]
I decided it was easier to implement that outside of django-rest-framework. The download is accessible at:

http://epu-index.herokuapp.com/epu-csv

It uses HTTP streaming to ensure it works well when the data volume gets bigger.
