### ISSUE TITLE
REST endpoint for getting articles

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#25]
The users need to be able to fetch newest articles for their classification algorithms. They should be able to get these articles using the REST interface with a GET method and after **authentication**. The endpoint should accept two parameters `from` and `to` both accepting dates in iso format (yyyy-mm-dd). The articles returned should include articles on the `from` and the `to` date.

The resulting data should look like:

```
{
    "records": [
        {
            "id": 3, # database id. used for updating (see issue #19)
            "title": "this is the title",
            "intro": "intro text",
            "text": "this is text",
            "published_at": datetime, # as yyyy-mm-dd hh:mm:ss
            "url": url,
            "journal": "the journal"
        },
        ...
    ]
}
```

**Comment by peterdesmet** [comment]
I assume your closing this as the actual requirements are recorded in #46?

**Comment by bartaelterman** [comment]
Yes. This endpoint was meant to be used by matlab scripts and required authentication. I consider the one documented in #46 a different endpoint.
