### ISSUE TITLE
Create main line chart

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/epu-index#26]
The main line chart shows the epu-index for one year.

* [x] Data range: fixed at one year
* [x] Data resolution: one day
* [x] X-axis labels: YYYY-MM
* [x] Y-axis labels: default
* [x] Y-axis: dynamic range
* [x] Hoover: show YYYY-MM-DD and epu-index in tooltip
* [x] Width: 760px (to fit inside website)

**Comment by peterdesmet** [comment]
Should epu-index be rounded on display? If so, how many decimals?

![screen shot 2015-07-07 at 17 38 46](https://cloud.githubusercontent.com/assets/600993/8550134/04e860a0-24cf-11e5-975a-02b4939d6eea.png)

**Comment by peterdesmet** [comment]
Final result:

![screen shot 2015-07-08 at 14 26 44](https://cloud.githubusercontent.com/assets/600993/8569979/50b72fda-257d-11e5-94a0-8f2413905adf.png)

Question regarding rounding remains.

**Comment by bartaelterman** [comment]
I would personally round. As the epu index for one day actually means "the average number of positive articles per journal", I think two decimal characters will suffice.

**Comment by peterdesmet** [comment]
Now rounded to 2 in tooltip (still exact value in chart): bc2ab535294f2f18c70c4d87ba7039e709046c6e
