### ISSUE TITLE
Create sub line chart

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/epu-index#27]
The sub line chart shows the epu-index for the whole date range.

* [x] Data range: all data (15 years)
* [x] Data resolution: one month
* [x] Aggregation: average for one month
* [x] X-axis labels: YYYY
* [x] Y-axis labels: default?
* [x] Y-axis: dynamic range
* [x] Disable hoover
* [x] Width: 760px (to fit inside website)

**Comment by peterdesmet** [comment]
@bartaelterman, One x-axis tick per month = quite a lot of ticks. Better to create one per year / half-year? Idem for text labels: only show year, for every year?

![schermafbeelding 2015-07-06 om 12 07 07](https://cloud.githubusercontent.com/assets/600993/8520080/9075b92c-23d7-11e5-80e4-30fe7d4765cd.png)

**Comment by bartaelterman** [comment]
Indeed, one per month is not informative. I would say one per year and only show the year in the tick label.

**Comment by peterdesmet** [comment]
![schermafbeelding 2015-07-06 om 15 46 12](https://cloud.githubusercontent.com/assets/600993/8523529/349cab5a-23f6-11e5-93b4-6e3410331339.png)

Year labels now correspond with January 1st. Is dynamic.

**Comment by bartaelterman** [comment]
nice. Looks slick!

**Comment by peterdesmet** [comment]
Final result:

![screen shot 2015-07-08 at 14 25 21](https://cloud.githubusercontent.com/assets/600993/8569964/2470b82e-257d-11e5-96b1-711ccd9471f3.png)

Using grid lines to indicate selection as region API is buggy.
