### ISSUE TITLE
Include charts in website

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/epu-index#29]
The charts will be displayed on the [Applied Data Mining website](http://www.applieddatamining.com/cms/)

* [x] Create page in Drupal
* [x] Add necessary html
* [x] Add necessary css (inline)
* [x] Add necessary js (inline)
* [x] Add page to main menu as `EPU`

We could also host css and js elsewhere that is easily accessible?

**Comment by peterdesmet** [comment]
HTML + CSS structure of website used in 11c778d4d454cfb3a099d0d91ad178e5c3e4d4eb

**Comment by bartaelterman** [comment]
Should add the menu link. Be careful with enters in paragraphs. Drupal replaces those by `<br>` tags which looks silly if you don't expect this.
