### ISSUE TITLE
Create a word cloud

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/epu-index#31]
Create a word cloud below the line charts:

* [x] Position: not defined
* [x] Word orientation: not defined
* [x] Word colour: not defined
* [x] Maximum number of words: not defined

**Comment by peterdesmet** [comment]
* The word cloud now appears full width, under the highest ranking article.
* The word orientation is defined by an array `angles`, which now contains `[-90, -45, 0]`
* The word colour is the text colour of the parent div for all words. Colour variation is not used, as is does not add any information and might be confusing.
* The maximum number of words will be set in the API call. I currently tested with 40 words.

The text size is scaled over the whole count range. So even if count is 1-4 or 1-4000, the scale will be a linear range between `minFontSize` (10) and `maxFontSize`(60). D3 is awesome that way!

![screen shot 2015-08-10 at 13 37 10](https://cloud.githubusercontent.com/assets/600993/9170649/f09a1a7a-3f64-11e5-80e5-12745c99e43e.png)

Only thing left to do: use the correct API #8 and call on user actions too.

**Comment by peterdesmet** [comment]
@bartaelterman, please ask feedback regarding the **layout** of the word cloud to the users on Monday.

**Comment by bartaelterman** [comment]
Feedback from users needed on layout.

**Comment by bartaelterman** [comment]
@peterdesmet Comments from the users:

* Drop the -45 angle
* Use a different font (they liked the one on the [d3-cloud page](https://github.com/jasondavies/d3-cloud) better)
* Use some colors.

They did not have immediate pointers (*this* font or *those* colors) so I would ask you to create a new suggestion based on this feedback that you think looks really nice.

**Comment by peterdesmet** [comment]
This issue can be closed after feedback on the second version by @bartaelterman

**Comment by bartaelterman** [comment]
Font, angles and colors updated as requested by client. Result:

![word_cloud](https://cloud.githubusercontent.com/assets/2742677/9846379/2776ded8-5ad2-11e5-8d1b-f53beaa8d855.png)
