### ISSUE TITLE
Provide data for word cloud

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/epu-index#32]
The word cloud will show the highest ranking words per day or per year:

* [ ] Only show positive words (> 0)
* [ ] Exclude stop words
* [ ] Word cloud can retrieve words for a year
* [ ] Word cloud can retrieve words for a day

**Comment by peterdesmet** [comment]
Do we already have those data?

**Comment by bartaelterman** [comment]
No, I have a list of articles but we still need to migrate them into the app. You can however use the admin interface to manually add some test articles. But we don't have an endpoint for this either.

**Comment by bartaelterman** [comment]
Issue for the endpoint: #8

**Comment by bartaelterman** [comment]
In fact, there is nothing left in this issue that is not covered by #8. Closing this issue as `wontfix`.
