### ISSUE TITLE
Click on main line chart triggers update in word cloud

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/epu-index#34]
* [ ] When a user clicks a point on the main line chart, the word cloud retrieves and shows the highest ranking words for that day.
* [x] This click can only be undone by clicking another point or brushing (see #33).

**Comment by peterdesmet** [comment]
Blocked by #8

**Comment by peterdesmet** [comment]
I can't seem to find days with data.

**Comment by bartaelterman** [comment]
2012-09-10 for example. I tested this, and it works.

You can always view them in the admin interface.
