### ISSUE TITLE
Import journals in database

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#50]

**Comment by bartaelterman** [comment]
I have a csvfile with news journals. These should be imported in the application.

Column 1: name
Column 2: spider_name

Delimiter: ";"

**Comment by bartaelterman** [comment]
I needed a data migration script for developement. Maybe this can help: https://github.com/Datafable/epu-index/blob/master/tmp/migrate_data.py

**Comment by niconoe** [comment]
Command implemented. Two addiditonal questions:

- Should I run it on Heroku now with the journals.csv file from old_data (Google Docs folder)?
- For now, the command expects the CSV dialect to be the one from old_data/journals.csv (no header line, ; separator, ...). If we ever need more flexibility, tell me and I'll implement something more sophisticated.

**Comment by bartaelterman** [comment]
Thanks!

* Yes, should be run on Heroku.
* No, no more flexibility is needed for this.

**Comment by niconoe** [comment]
Data loaded on Heroku. Please note there was already an entry for "Het Laatste Nieuws", I didn't dared to delete it since there were linked articles!

**Comment by bartaelterman** [comment]
Ok. Actually that's all dummy data. So next time, the table can be trunced before uploading new data. I did not consider that database as production so far.
