### ISSUE TITLE
Add `epu_score` to `Article` model

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#52]
# Questions

- How many decimal places are needed?
- What do we fill in for articles scraped before 2013? Note that if we leave this field empty for those articles, that these articles can't be used for the word could.

**Comment by peterdesmet** [comment]
If articles before 2013 are not scored (recommended), we probably should not provide a highest scoring article for those dates either, no?

**Comment by bartaelterman** [comment]
Added this field to the article model (3c241a550791928224d77c226d0142f47a037ad1).

If articles before 2013 will not get a score, I think we indeed need another solution for the front end, as this affects a large part of the data. Maybe we can suggest to show all positive articles?

**Comment by bartaelterman** [comment]
- Number of decimal places in database: 5
- Number of decimal places on front end: 2
- Number of decimal places in download: 5

**Comment by bartaelterman** [comment]
Customer will send us a file with scores of old articles.
