### ISSUE TITLE
Make sure articles are unique

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#54]
- **Option 1:** Set a unique constraint on the articles url. Problem: articles scraped before 2013 don't have a url. (see also #53)
- **Option 2:** Set a unique constraint on a combination of the fields `news_journal`, `published_at` and `title`

**Comment by bartaelterman** [comment]
Urls are not an option (see #53 ) so we'll have to go for option 2.

@niconoe can we add such a constraint in the models file?

**Comment by niconoe** [comment]
Yes, it can be implemented using [unique_together](https://docs.djangoproject.com/en/1.8/ref/models/options/#unique-together), and Django will create constraint at the database level. Does that looks good?

**Comment by bartaelterman** [comment]
Excellent!

**Comment by peterdesmet** [comment]
Since URLs are still mandatory, I cannot test if articles without URL are displayed nicely on the front end. Don't close this issue until this has been tested.

**Comment by niconoe** [comment]
The URL is now optional, and unique_together constraint is set (everything deployed to Heroku). I guess this issue + #53 + #63 are now solved, please test!

**Comment by peterdesmet** [comment]
Frontend works: only shows newspaper name, without link if no URL is available.
