### ISSUE TITLE
Alert needed when scraper fails?

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#57]
Should the user be alerted (via email for instance) if a scraper fails?

**Comment by bartaelterman** [comment]
Here is what we will do:

A separate check script will run after all scrapers have run. If one spider returned 0 articles for 7 consecutive days, an email alert is sent.

**Comment by bartaelterman** [comment]
@niconoe I think another django command would be best for this, so I'll assign you. Nevetheless, I can help with the code to email (example [here](https://github.com/peterdesmet/nlp-data-store/blob/master/streamers/TwitterStreamer/TwitterStreamer.py#L59))

**Comment by niconoe** [comment]
This is implemented, it use the Django machinery for sending mails, so at the deployment this will have to be configured/tested the Django way.

**Comment by bartaelterman** [comment]
Excellent. I've create an account for the client. Will test it.

**Comment by bartaelterman** [comment]
Shouldn't it get a password somewhere?

**Comment by niconoe** [comment]
In production, I guess you would use SMTP and then have to configure the following settings: https://docs.djangoproject.com/en/1.8/topics/email/#smtp-backend (probably at least the first four settings).

So far, I tested it locally using the [console backend](https://docs.djangoproject.com/en/1.8/topics/email/#console-backend).

**Comment by bartaelterman** [comment]
:+1: 

Indeed the first four settings need to be set ([this](https://support.google.com/a/answer/176600?hl=en) can help). Also `EMAIL_USE_SSL` needs to be set to `True`. Besides setting these settings, no other action is needed.

Tested it, and emails are indeed sent as expected!
