### ISSUE TITLE
Should Django admin be bootstrapped?

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/epu-index#62]
Just like for NLP we could make the Django admin more bootstrappy by using a plugin.

**Comment by niconoe** [comment]
I'm not strongly against it if you think it greatly enhances the user experience, but I generally don't do it by default since every dependency has some maintenance cost.

**Comment by peterdesmet** [comment]
Maybe ask the users if you meet them on Monday.

**Comment by bartaelterman** [comment]
I'll ask them.

**Comment by bartaelterman** [comment]
Not needed.
