### ISSUE TITLE
Remove numbers and single letter worsd from word cloud

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#74]

**Comment by bartaelterman** [comment]
@niconoe after a second thought it might be better to implement this in the new django command. Every number (so `[0-9]+`) should be removed from the word frequencies.

I'll assign this to you.

**Comment by bartaelterman** [comment]
Or implement it in the endpoint logic. So it's ok to save them, but don't show them in the word cloud.

**Comment by niconoe** [comment]
It's implemented in the endpoint logic, and seems to work fine! It is also deployed in production.

Should we close this ticket, @bartaelterman?

**Comment by bartaelterman** [comment]
Quick look. Numbers are indeed gone, but the single letter words are still there. Could you fix that? When done, you can close this ticket.

**Comment by niconoe** [comment]
Indeed, I missed the edit! It's now fixed.
