### ISSUE TITLE
Cannot access webapp API from JavaScript

### ISSUE THREAD

**Issue by bartaelterman** [Datafable/epu-index#9]
When I try to access the API using JavaScript, I get the following error:

`XMLHttpRequest cannot load http://epu-index.herokuapp.com/api/epu/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:...' is therefore not allowed access.`

Apparently, you need to enable these type of connections in the Django REST framework. (See [this page](http://www.django-rest-framework.org/topics/ajax-csrf-cors/#cors) under `Cross-Origin Resource Sharing`. It should be managed with [this package](https://github.com/ottoyiu/django-cors-headers/).

**Comment by niconoe** [comment]
Allright ! I guess we don't need to protect from anything and so I can (for now at least) to give access whatever the origin ?

**Comment by niconoe** [comment]
Fixed, tell me if anything's wrong!

**Comment by bartaelterman** [comment]
certainly for GET calls. I don't know how specific you can tune this.
